layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

projects:
  forks: false
  sort_by: pushed
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
      - website
      - dotfiles
      - homebrew-repo

social_media:
  linkedin: johnnyhuy
  stackoverflow: 7506439
  website: https://johnnyhuy.com

topics:
  - name: Kubernetes
    web_url: https://github.com/topics/kubernetes
    image_url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.svg

