apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: website
  title: Website
  description: The portfolio website
  tags:
    - ruby
spec:
  type: website
  lifecycle: production
  owner: johnnyhuy