name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Yarn install with caching
        uses: bahmutov/npm-install@v1.1.0

      - name: Build assets
        run: yarn build

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Semantic release
        run: yarn release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}